# Generated by Django 5.0.3 on 2024-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingtool', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divider_str', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'dividers',
                'managed': False,
            },
        ),
    ]
