# Generated by Django 5.0.3 on 2024-05-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingtool', '0004_dividers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dividers',
        ),
    ]
